In [14]:
import numpy as np

In [15]:
import bokeh.plotting

In [16]:
bokeh.plotting.output_notebook()

Loading BokehJS ...

In [17]:
from bokeh.palettes import Category10_9 as palette

In [2]:
import sklearn as sk
from sklearn import datasets
from sklearn import preprocessing

In [3]:
# from sklearn.cross_validation import train_test_split
# from the docs, this new version should run code using the preious version
from sklearn.model_selection import train_test_split  

In [4]:
iris = datasets.load_iris()
X_iris, y_iris = iris.data, iris.target
print(X_iris.shape, y_iris.shape)

(150, 4) (150,)


In [5]:
y_iris

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
X_iris

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [19]:
X, y = X_iris[:, :2], y_iris
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.25, random_state=33)

In [20]:
print(X_train.shape, y_train.shape)

(112, 2) (112,)


Standardize the features

In [21]:
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [33]:
colors = ['red', 'greenyellow', 'blue']
p = bokeh.plotting.figure(
    title='Iris',
    x_axis_label='Sepal length',
    y_axis_label='Sepal width',
    width=400, height=350,
)

for i in set(y_train):
    mask = y_train == i
    xs = X_train[:, 0][mask]
    ys = X_train[:, 1][mask]
    p.circle(xs, ys, color=colors[i], 
             legend=iris.target_names[i])

bokeh.plotting.show(p)

Create a linear classification model that identifies setosa/not-setosa flowers.

In [34]:
from sklearn.linear_model import SGDClassifier

In [44]:
clf = SGDClassifier(max_iter=1000)
clf.fit(X_train, y_train)

print(clf.coef_)

print(clf.intercept_)

[[-7.59295626  3.54627558]
 [ 0.16618199 -1.52646942]
 [ 1.64327365  0.17280155]]
[-4.76956293 -0.98021878 -1.11084284]


In [47]:
x_min, x_max = X_train[:, 0].min() - 0.5, X_train[:, 0].max() + 0.5
y_min, y_max = X_train[:, 1].min() - 0.5, X_train[:, 1].max() + 0.5
xs = np.arange(x_min, x_max, 0.5)

In [49]:
from bokeh.layouts import gridplot

In [54]:
p0 = bokeh.plotting.figure(
    title='Class 0 versus the rest',
    x_axis_label='Sepal length',
    y_axis_label='Sepal width',
    width=200, height=300,
)
p1 = bokeh.plotting.figure(
    title='Class 1 versus the rest',
    x_axis_label='Sepal length',
    width=200, height=300,
    x_range=p0.x_range, y_range=p0.y_range,
)
p2 = bokeh.plotting.figure(
    title='Class 2 versus the rest',
    x_axis_label='Sepal length',
    width=200, height=300,
    x_range=p0.x_range, y_range=p0.y_range
)
ps = [p0, p1, p2]

for i in set(y_train):
    mask = y_train == i
    xs = X_train[:, 0][mask]
    ys = X_train[:, 1][mask]
    p0.circle(xs, ys, color=colors[i])
    p1.circle(xs, ys, color=colors[i])
    p2.circle(xs, ys, color=colors[i])
    #           legend=iris.target_names[i])
    ys = (-clf.intercept_[i] - xs * clf.coef_[i, 0]) / clf.coef_[i, 1]
    ps[i].line(xs, ys)
p0.y_range
    
grid = gridplot([ps])
bokeh.plotting.show(grid)

Suppose we have a new flower with a sepal width of 4.7 and a sepal length of 3.1.  What is the predicted class?

In [63]:
new_flower = [4.7, 3.1]
scaled = scaler.transform([new_flower])
print('scaled size: {}, {}'.format(scaled[0, 0], scaled[0, 1]))
clf.predict(scaled)

scaled size: -1.2595014605312675, 0.09442167641138198


array([0])

What is this in scaled units?

In [66]:
scaled

array([[-1.25950146,  0.09442168]])

This classifier is simply picking the line that is the furthes from the point.

In [67]:
print(clf.decision_function(scaled))

[[ 5.12862185 -1.33365704 -3.1642322 ]]
